from dash.html import Div, Button, Img
from dash.dcc import Tabs, Tab, Input, Upload, Store, Dropdown, Graph
from dash_svg import Svg, Path, Line


def getLayoutFormated():
    return Div(
        [
            Div(
                children=[
                    Upload(
                        children=[
                            Div(
                                children=[
                                    Div(
                                        children=[],
                                        id="rectangle-31",
                                        className="rectangle-31",
                                    ),
                                    Div(
                                        children=[],
                                        id="rectangle-32",
                                        className="rectangle-32",
                                    ),
                                ],
                                id="group-43",
                                className="group-43",
                            ),
                            Div(
                                children=["Import Data"],
                                id="import-data",
                                className="import-data",
                            ),
                        ],
                        id="import-data-upload-dash_UPLOAD",
                        className="import-data-upload-dash",
                        multiple=True,
                    ),
                    Div(
                        children=[
                            Div(
                                children=[
                                    Div(
                                        children=[
                                            Div(
                                                children=[
                                                    Div(
                                                        children=["Time History"],
                                                        id="time-history",
                                                        className="time-history",
                                                    )
                                                ],
                                                id="time-history-title",
                                                className="time-history-title",
                                            ),
                                            Graph(
                                                id="time-history-graph-dash_GRAPH",
                                                className="time-history-graph-dash",
                                                figure={},
                                            ),
                                        ],
                                        id="time-history-frame",
                                        className="time-history-frame",
                                    ),
                                    Div(
                                        children=[
                                            Div(
                                                children=[
                                                    Div(
                                                        children=["Data Decomposition"],
                                                        id="data-decomposition",
                                                        className="data-decomposition",
                                                    )
                                                ],
                                                id="data-decomposition-title",
                                                className="data-decomposition-title",
                                            ),
                                            Graph(
                                                id="data-decomposition-graph-dash_GRAPH",
                                                className="data-decomposition-graph-dash",
                                                figure={},
                                            ),
                                        ],
                                        id="data-decomposition-frame",
                                        className="data-decomposition-frame",
                                    ),
                                ],
                                id="graphs",
                                className="graphs",
                            ),
                            Div(
                                children=[
                                    Div(
                                        children=[
                                            Div(
                                                children=["Data Report"],
                                                id="data-report",
                                                className="data-report",
                                            )
                                        ],
                                        id="data-report-title",
                                        className="data-report-title",
                                    ),
                                    Div(
                                        children=[
                                            Div(
                                                children=["AAAAAAAAAAAAAAAAAAAAAAAAAA"],
                                                id="aaaaaaaaaaaaaaaaaaaaaaaaaa",
                                                className="aaaaaaaaaaaaaaaaaaaaaaaaaa",
                                            )
                                        ],
                                        id="data-report-info-box",
                                        className="data-report-info-box",
                                    ),
                                ],
                                id="data-report-frame",
                                className="data-report-frame",
                            ),
                        ],
                        id="data-input-frame",
                        className="data-input-frame",
                    ),
                ],
                id="box-input-data-test",
                className="box-input-data-test",
            )
        ]
    )
