from dash.html import Div, Button, Img
from dash.dcc import Tabs, Tab, Input, Upload, Store, Dropdown
from dash_svg import Svg, Path, Line


def getLayoutFormated():
    return Div(
        [
            Store('store_input_data_filePath'),
            Div(
                children=[
                    Div(
                        children=[
                            Div(
                                children=[
                                    Div(
                                        children=[
                                            Div(
                                                children=[],
                                                id="rectangle-4",
                                                className="rectangle-4",
                                            ),
                                            Div(
                                                children=[],
                                                id="rectangle-5",
                                                className="rectangle-5",
                                            ),
                                        ],
                                        id="retangles-logo",
                                        className="retangles-logo",
                                    ),
                                    Div(
                                        children=[
                                            Div(
                                                children=["D2P"],
                                                id="d-2-p",
                                                className="d-2-p",
                                            ),
                                            Div(
                                                children=["Data to Modeling"],
                                                id="data-to-modeling",
                                                className="data-to-modeling",
                                            ),
                                        ],
                                        id="frame-2",
                                        className="frame-2",
                                    ),
                                ],
                                id="logo-box",
                                className="logo-box",
                            )
                        ],
                        id="upper-header",
                        className="upper-header",
                    ),
                    Div(
                        children=[
                            Div(
                                children=[
                                    Div(
                                        children=[
                                            Svg(
                                                children=[
                                                    Path(
                                                        d="M0 0H119H244V502.588V570.59V712H0V0Z",
                                                        fill="#3A2EC8",
                                                    )
                                                ],
                                                id="frame-svg-selected-tab_SVG",
                                                className="frame-svg-selected-tab",
                                                fill="none",
                                                height="712",
                                                width="244",
                                                xmlns="http://www.w3.org/2000/svg",
                                            ),
                                            Button(
                                                children=[
                                                    Svg(
                                                        children=[
                                                            Line(
                                                                stroke="#8B2F2F",
                                                                strokeWidth="2",
                                                                transform="matrix(0.757602 -0.652716 0.72495 0.688801 9 12.7849)",
                                                                x1="1",
                                                                x2="10.5971",
                                                                y1="-1",
                                                                y2="-1",
                                                            ),
                                                            Path(
                                                                d="M16.5508 4.71436L19.7087 7.36947",
                                                                stroke="#8B2F2F",
                                                                strokeWidth="2",
                                                            ),
                                                            Line(
                                                                stroke="#8B2F2F",
                                                                strokeWidth="2",
                                                                transform="matrix(0.810068 -0.586335 0.662404 0.749147 19.7087 7.57153)",
                                                                x1="1",
                                                                x2="6.79661",
                                                                y1="-1",
                                                                y2="-1",
                                                            ),
                                                            Line(
                                                                stroke="#FEBA08",
                                                                strokeWidth="2",
                                                                x1="4.78955",
                                                                x2="4.78955",
                                                                y1="1",
                                                                y2="19",
                                                            ),
                                                            Line(
                                                                stroke="#FEBA08",
                                                                strokeWidth="2",
                                                                x1="1",
                                                                x2="23",
                                                                y1="16.1428",
                                                                y2="16.1428",
                                                            ),
                                                        ],
                                                        id="icon-time-series_SVG",
                                                        className="icon-time-series",
                                                        fill="none",
                                                        height="20",
                                                        width="27",
                                                        xmlns="http://www.w3.org/2000/svg",
                                                    ),
                                                    Div(
                                                        children=["Time Series"],
                                                        id="time-series",
                                                        className="time-series",
                                                    ),
                                                ],
                                                id="time-series-button-dash_BUTTON",
                                                className="time-series-button-dash",
                                                n_clicks=0,
                                            ),
                                            Button(
                                                children=[
                                                    Svg(
                                                        children=[
                                                            Path(
                                                                d="M5.47688 9.60737H10.9538M12.7794 13.2586H3.65126C2.68288 13.2586 1.75417 12.8739 1.06943 12.1892C0.384685 11.5045 7.92132e-10 10.5757 7.92132e-10 9.60737V3.86395C-1.3075e-05 3.23613 0.161857 2.61891 0.469979 2.0719C0.778101 1.5249 1.22206 1.06658 1.75899 0.741211L3.65126 2.0719C4.22187 1.72613 7.3328 4.94679 8 4.94679C8.6672 4.94679 12.2088 1.72613 12.7794 2.07191L14.6717 0.741211C15.2085 1.0665 15.6523 1.52467 15.9604 2.07151C16.2686 2.61834 16.4305 3.23537 16.4307 3.86303V9.60737C16.4307 10.5757 16.046 11.5045 15.3612 12.1892C14.6765 12.8739 13.7478 13.2586 12.7794 13.2586Z",
                                                                stroke="white",
                                                                strokeLinecap="round",
                                                                strokeLinejoin="round",
                                                                strokeWidth="1.36922",
                                                            )
                                                        ],
                                                        id="icon-data-reg_SVG",
                                                        className="icon-data-reg",
                                                        fill="none",
                                                        height="14",
                                                        width="17",
                                                        xmlns="http://www.w3.org/2000/svg",
                                                    ),
                                                    Div(
                                                        children=[
                                                            "Data",
                                                            Div([]),
                                                            "Regression",
                                                        ],
                                                        id="data-regression",
                                                        className="data-regression",
                                                    ),
                                                ],
                                                id="data-reg-button-dash_BUTTON",
                                                className="data-reg-button-dash",
                                                n_clicks=0,
                                            ),
                                            Button(
                                                children=[
                                                    Div(
                                                        children=[
                                                            Div(
                                                                children=[],
                                                                id="yeloow",
                                                                className="yeloow",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="blue",
                                                                className="blue",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="green",
                                                                className="green",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="red",
                                                                className="red",
                                                            ),
                                                        ],
                                                        id="icon-clustering",
                                                        className="icon-clustering",
                                                    ),
                                                    Div(
                                                        children=["Clustering"],
                                                        id="clustering",
                                                        className="clustering",
                                                    ),
                                                ],
                                                id="clustering-button-dash_BUTTON",
                                                className="clustering-button-dash",
                                                n_clicks=0,
                                            ),
                                            Button(
                                                children=[
                                                    Svg(
                                                        children=[
                                                            Path(
                                                                d="M12.4444 14.4167C12.4444 14.8769 12.6932 15.25 13 15.25C13.3068 15.25 13.5555 14.8769 13.5555 14.4167V8.58325H17.4444C17.7513 8.58325 18 8.21017 18 7.74992C18 7.28967 17.7513 6.91658 17.4444 6.91658H13.5555V1.08333C13.5555 0.6231 13.3068 0.25 13 0.25C12.6932 0.25 12.4444 0.6231 12.4444 1.08333V6.91658H8.55556C8.24873 6.91658 8 7.28967 8 7.74992C8 8.21017 8.24873 8.58325 8.55556 8.58325H12.4444V14.4167Z",
                                                                fill="#FEBA08",
                                                            ),
                                                            Path(
                                                                d="M12.4444 25.8611C12.4444 26.352 12.6932 26.75 13 26.75C13.3068 26.75 13.5555 26.352 13.5555 25.8611V19.6388H17.4444C17.7513 19.6388 18 19.2408 18 18.7499C18 18.259 17.7513 17.861 17.4444 17.861H13.5555V11.6389C13.5555 11.148 13.3068 10.75 13 10.75C12.6932 10.75 12.4444 11.148 12.4444 11.6389V17.861H8.55556C8.24873 17.861 8 18.259 8 18.7499C8 19.2408 8.24873 19.6388 8.55556 19.6388H12.4444V25.8611Z",
                                                                fill="#FEBA08",
                                                            ),
                                                            Path(
                                                                d="M4.44443 25.8611C4.44443 26.352 4.69321 26.75 4.99999 26.75C5.30682 26.75 5.55554 26.352 5.55554 25.8611V19.6388H9.44444C9.75128 19.6388 10 19.2408 10 18.7499C10 18.259 9.75128 17.861 9.44444 17.861H5.55554V11.6389C5.55554 11.148 5.30682 10.75 4.99999 10.75C4.69321 10.75 4.44443 11.148 4.44443 11.6389V17.861H0.555557C0.248734 17.861 0 18.259 0 18.7499C0 19.2408 0.248734 19.6388 0.555557 19.6388H4.44443V25.8611Z",
                                                                fill="#FEBA08",
                                                            ),
                                                            Path(
                                                                d="M21.4444 25.8611C21.4444 26.352 21.6932 26.75 22 26.75C22.3068 26.75 22.5555 26.352 22.5555 25.8611V19.6388H26.4444C26.7513 19.6388 27 19.2408 27 18.7499C27 18.259 26.7513 17.861 26.4444 17.861H22.5555V11.6389C22.5555 11.148 22.3068 10.75 22 10.75C21.6932 10.75 21.4444 11.148 21.4444 11.6389V17.861H17.5556C17.2487 17.861 17 18.259 17 18.7499C17 19.2408 17.2487 19.6388 17.5556 19.6388H21.4444V25.8611Z",
                                                                fill="#FEBA08",
                                                            ),
                                                            Path(
                                                                d="M12.4444 36.9167C12.4444 37.3769 12.6932 37.75 13 37.75C13.3068 37.75 13.5555 37.3769 13.5555 36.9167V31.0833H17.4444C17.7513 31.0833 18 30.7102 18 30.2499C18 29.7897 17.7513 29.4166 17.4444 29.4166H13.5555V23.5833C13.5555 23.1231 13.3068 22.75 13 22.75C12.6932 22.75 12.4444 23.1231 12.4444 23.5833V29.4166H8.55556C8.24873 29.4166 8 29.7897 8 30.2499C8 30.7102 8.24873 31.0833 8.55556 31.0833H12.4444V36.9167Z",
                                                                fill="#FEBA08",
                                                            ),
                                                        ],
                                                        id="icon-neural-network_SVG",
                                                        className="icon-neural-network",
                                                        fill="none",
                                                        height="38",
                                                        width="27",
                                                        xmlns="http://www.w3.org/2000/svg",
                                                    ),
                                                    Div(
                                                        children=["Neural Network"],
                                                        id="neural-network",
                                                        className="neural-network",
                                                    ),
                                                ],
                                                id="neural-net-button-dash_BUTTON",
                                                className="neural-net-button-dash",
                                                n_clicks=0,
                                            ),
                                            Button(
                                                children=[
                                                    Div(
                                                        children=[
                                                            Div(
                                                                children=[],
                                                                id="yeloow2",
                                                                className="yeloow2",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="blue2",
                                                                className="blue2",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="green2",
                                                                className="green2",
                                                            ),
                                                            Div(
                                                                children=[],
                                                                id="red2",
                                                                className="red2",
                                                            ),
                                                        ],
                                                        id="icon-img-recognition",
                                                        className="icon-img-recognition",
                                                    ),
                                                    Div(
                                                        children=["Image recognition"],
                                                        id="image-recognition",
                                                        className="image-recognition",
                                                    ),
                                                ],
                                                id="img-recogn-button-dash_BUTTON",
                                                className="img-recogn-button-dash",
                                                n_clicks=0,
                                            ),
                                        ],
                                        id="side-menu-tabs",
                                        className="side-menu-tabs",
                                    ),
                                    Div(children=[], id="frame-6", className="frame-6"),
                                ],
                                id="side-menu",
                                className="side-menu",
                            ),
                            Div(
                                children=[
                                    Div(children=[], id="frame-5", className="frame-5")
                                ],
                                id="side-tabs-result",
                                className="side-tabs-result",
                            ),
                        ],
                        id="website-body",
                        className="website-body",
                    ),
                ],
                id="main-aplication",
                className="main-aplication",
            )
        ]
    )
